### ISSUE TITLE
Issues with Guava on EMR?

### ISSUE THREAD

**Issue by anuras** [audienceproject/spark-dynamodb#29]
I'm getting `java.lang.NoSuchMethodError: com.google.common.util.concurrent.RateLimiter.acquire(I)D` errors
when running `.write.dynamodb()` on EMR. Running locally I'm not having any trouble.
I presume that is coming from Guava library.
I noticed this issue has been escalated and closed in the past, but I'm having issues with it still.
I've tried different versions (`0.4.1` and `0.3.6`) as well as different emr releases (`5.22.0` and `5.20.0`) the result is always the same. I don't think I'm pulling in Guava from anywhere else as by now I've only left the `"com.audienceproject" %% "spark-dynamodb" % "0.4.1"` in my dependencies.
May I ask what is the target/intended EMR image version for the latest release of the lib?

**Comment by jacobfi** [comment]
Hi anuras
Yes Guava dependency is always tricky. I'm half tempted to copy-pasting the rate limiter implementation instead of depending on the whole library.
`spark-dynamodb` is intended to work with version `14.0.1` of Guava, because this is what ships with Spark. I believe EMR installs a slightly newer version, but for the sake of the rate limiter it should be compatible.

What applications other than Spark do you have installed on the cluster?
Maybe also look in the environment tab of the Spark UI, it should list all of the dependencies on your class path.

**Comment by cosmincatalin** [comment]
Hi @anuras , I will close this for now. If you have further questions, you're welcome to reopen the issue.

**Comment by AceHack** [comment]
Even guava 15 or 16 breaks this, please copy paste rate limiter as you stated.

**Comment by cosmincatalin** [comment]
https://github.com/audienceproject/spark-dynamodb/issues/35

**Comment by tabughofaupgrade** [comment]
a better solution is to shade the gauva library within your jar. use the sbt shade plugin

**Comment by woj-i** [comment]
Hi! I use `com.amazonaws:DynamoDBLocal:1.11.477` and it cause the same conflict of guava: `java.lang.NoSuchMethodError: com.google.common.util.concurrent.RateLimiter.acquire(I)V
	at com.audienceproject.spark.dynamodb.connector`

**Comment by cosmincatalin** [comment]
Please follow #35 . We're now in the process of pulling out Guava and releasing a brand new version of the connector. I expect that next week we'll be able to release, and all of these issues will be a thing of the past.
